const preConfigurations = {
  "1 Controle entré": { local: 15, total: 10163 },
  "1 linge sale": { local: 63, total: 5507 },
  "non triés": { local: 133, total: 1044 },
  "convoyeur inclinné": { local: 10, total: 213 },
  "Convoyeur incliné bleu": { local: 49, total: 49 },
  "INC 1 convoyeur inclinée vers étage ": { local: 64, total: 64 },
  "INC 2 convoyeur inclinée vers pesée": { local: 15, total: 15 },
  "INC 3 convoyeur inclinée descente trolley vide": { local: 1, total: 1 },
  "INC 4 convoyeur inclinée sortie nappe inférieur": { local: 4, total: 4 },
  "INC 5 convoyeur inclinée entre industriel et résident": { local: 4, total: 4 },
  "INC 6 convoyeur inclinée après décroche sac": { local: 62, total: 62 },
  "INC 7 convoyeur inclinée nappe inférieur vers industriel": { local: 4, total: 4 },
  "Décroche sac": { local: 62, total: 62 },
  "Pesée nappe inférieur (NT2)": { local: 25, total: 25 },
  "Pesée nappe supérieur (NT1)": { local: 45, total: 45 },
  "Poste d\'accrochage": { local: 181, total: 181 },
  "station déchargement (DU...)": { local: 14, total: 186 },
  "DU1 poste de déchargement avec pré-stockage": { local: 20, total: 20 },
  "DU2 poste de déchargement avec pré-stockage": { local: 22, total: 22 },
  "DU3 poste de déchargement avec pré-stockage": { local: 44, total: 44 },
  "DU4 poste de déchargement avec pré-stockage": { local: 35, total: 35 },
  "DU6 poste de déchargement avec pré-stockage": { local: 51, total: 51 },
  "tampon stockage": { local: 5, total: 77 },
  "SRS 20 (stockage avant CI1)": { local: 3, total: 3 },
  "SRS 21 (stockage après CI1)": { local: 3, total: 3 },
  "SRS 22 (stockage avant pesée)": { local: 1, total: 1 },
  "SRS 23 (stockage avant pesée nappe inférieur)": { local: 13, total: 13 },
  "SRS 31 (stockage avant DU6)": { local: 6, total: 6 },
  "SRS 32 (stockage avant INC 5)": { local: 1, total: 1 },
  "Tampon 1 trolley vide ": { local: 8, total: 8 },
  "Tampon 2 trolley vide ": { local: 2, total: 2 },
  "Tampon 3 trolley vide ": { local: 2, total: 2 },
  "Tampon 4 trolley vide ": { local: 2, total: 2 },
  "Tampon draps alèses": { local: 1, total: 1 },
  "Tampon DU3": { local: 4, total: 4 },
  "Tampon DU4": { local: 2, total: 2 },
  "Tampon sac vide industriel (avant décroche sac)": { local: 17, total: 17 },
  "Tampon sac vide résident (avant décroche sac)": { local: 0, total: 0 },
  "Tampon trolley vide avant poste d\'accrochage": { local: 7, total: 7 },
  "voie de stockage": { local: 15, total: 122 },
  "Voie 01": { local: 16, total: 16 },
  "Voie 02": { local: 11, total: 11 },
  "Voie 03": { local: 8, total: 8 },
  "Voie 04": { local: 8, total: 8 },
  "Voie 05": { local: 10, total: 10 },
  "Voie 06": { local: 15, total: 15 },
  "Voie 07": { local: 5, total: 5 },
  "Voie 08": { local: 6, total: 6 },
  "Voie 09": { local: 1, total: 1 },
  "Voie 10": { local: 2, total: 2 },
  "Voie 11": { local: 6, total: 6 },
  "Voie 21": { local: 3, total: 3 },
  "Voie 22": { local: 2, total: 2 },
  "Voie 23": { local: 3, total: 3 },
  "Voie 24": { local: 1, total: 1 },
  "Voie 25": { local: 2, total: 2 },
  "Voie 26": { local: 2, total: 2 },
  "Voie 27": { local: 1, total: 1 },
  "Voie 28": { local: 0, total: 0 },
  "Voie 29": { local: 2, total: 2 },
  "Voie 30": { local: 3, total: 3 },
  "triés": { local: 33, total: 4143 },
  "nappe industriel": { local: 198, total: 3279 },
  "alvéoles": { local: 57, total: 153 },
  "Alvéole 01": { local: 74, total: 74 },
  "Alvéole 02": { local: 9, total: 9 },
  "Alvéole 03": { local: 18, total: 18 },
  "Alvéole 04": { local: 18, total: 18 },
  "Alvéole 05": { local: 115, total: 115 },
  "Alvéole 06": { local: 38, total: 38 },
  "Alvéole 07": { local: 66, total: 66 },
  "Alvéole 08": { local: 17, total: 17 },
  "Alvéole 09": { local: 45, total: 45 },
  "Alvéole 10": { local: 40, total: 40 },
  "Alvéole 11": { local: 91, total: 91 },
  "Alvéole 12": { local: 164, total: 164 },
  "futurail": { local: 261, total: 1364 },
  "aiguillage": { local: 73, total: 145 },
  "Aiguillage 3 voie sortie chargeur et voie de recyclage": { local: 21, total: 21 },
  "Aiguillage 3 voies sortie nappe": { local: 51, total: 51 },
  "Aiguillage entrée voie 1": { local: 0, total: 0 },
  "Aiguillage entrée voie 2": { local: 0, total: 0 },
  "Aiguillage entrée voie 3": { local: 0, total: 0 },
  "Aiguillage entrée voie 4": { local: 0, total: 0 },
  "Aiguillage sortie voie 1": { local: 0, total: 0 },
  "Aiguillage sortie voie 2": { local: 0, total: 0 },
  "Aiguillage sortie voie 3": { local: 0, total: 0 },
  "Aiguillage sortie voie 4": { local: 0, total: 0 },
  "Basculeur sling vide": { local: 66, total: 66 },
  "Chargeur de sac (sling)": { local: 295, total: 295 },
  "D1 dechargeur tunnel 10 ": { local: 173, total: 173 },
  "D2 dechargeur tunnel 12": { local: 180, total: 180 },
  "Décroche sacs": { local: 28, total: 28 },
  "LA1 (ascenceur avant voie de recyclage)": { local: 11, total: 11 },
  "Redresseur sling vide": { local: 298, total: 298 },
  "Tampon avant tunnel 10 (D1)": { local: 15, total: 15 },
  "Tampon avant tunnel 12 (D2)": { local: 20, total: 20 },
  "Tampon recyclage": { local: 95, total: 95 },
  "Tampon sling vide avant chargeur": { local: 9, total: 9 },
  "Tampon sling vide basculé": { local: 19, total: 19 },
  "Tampon sling vide sortie redresseur": { local: 3, total: 3 },
  "VC2 (descenceur avant tunnels)": { local: 50, total: 50 },
  "Voie 1": { local: 70, total: 70 },
  "Voie 2": { local: 19, total: 19 },
  "Voie 3": { local: 48, total: 48 },
  "Voie 4": { local: 90, total: 90 },
  "Voie 5": { local: 91, total: 91 },
  "tapis": { local: 128, total: 220 },
  "Tapis avant tapis incliné chargeur": { local: 18, total: 18 },
  "Tapis derrière alvéoles 1 a 5": { local: 53, total: 53 },
  "Tapis derrière alvéoles 11": { local: 50, total: 50 },
  "Tapis derrière alvéoles 12 ": { local: 20, total: 20 },
  "Tapis derrière alvéoles 6 a 10": { local: 46, total: 46 },
  "Tapis devant alvéoles": { local: 2, total: 2 },
  "Tapis incliné avant chargeur": { local: 20, total: 20 },
  "Tapis tri devant alvéoles entre industriel et résindent": { local: 6, total: 6 },
  "Tapis tri devant alvéoles résident": { local: 0, total: 0 },
  "nappe résident": { local: 131, total: 1868 },
  "Alvéole 1": { local: 9, total: 9 },
  "Alvéole 2": { local: 6, total: 6 },
  "Alvéole 3": { local: 24, total: 24 },
  "Alvéole 4": { local: 2, total: 2 },
  "Alvéole 5": { local: 23, total: 23 },
  "Alvéole 6": { local: 5, total: 5 },
  "Alvéole 7": { local: 5, total: 5 },
  "Alvéole 8": { local: 22, total: 22 },
  "By-pass tunnel 3 pour sling vide": { local: 3, total: 3 },
  "D3 dechargeur tunnel 3": { local: 201, total: 201 },
  "D4 dechargeur laveuses": { local: 56, total: 56 },
  "LU1 (chargeur de sac)": { local: 109, total: 109 },
  "MLA1 (ascenceur sortie tunnel 3)": { local: 63, total: 63 },
  "PLA1 (ascenceur sortie recyclage)": { local: 13, total: 13 },
  "Pré-stockage PLA1 sortie tampon 3": { local: 2, total: 2 },
  "Stockage sling plein après chargeur": { local: 0, total: 0 },
  "Tampon 1 (sortie voies et avant tunnel 3)": { local: 11, total: 11 },
  "Tampon 2 (sortie voies et avant laveuses)": { local: 40, total: 40 },
  "Tampon 3 (recyclage)": { local: 6, total: 6 },
  "Tampon laveuse": { local: 0, total: 0 },
  "Tampon sling vide": { local: 5, total: 5 },
  "Tampon tunnel 3": { local: 3, total: 3 },
  "T40.1 (tapis derrière alvéoles résident)": { local: 22, total: 22 },
  "T40.2 (tapis derrière alvéoles résident)": { local: 4, total: 4 },
  "T40.3 (tapis incliné avant chargeur)": { local: 13, total: 13 },
  "T40.4 (tapis vers industriel)": { local: 20, total: 20 },
  "T40.5 (tapis décatissage linge neuf)": { local: 33, total: 33 },
  "Tapis tri devant alvéole 11": { local: 0, total: 0 },
  "Tunnel de désinfection": { local: 257, total: 257 },
  "2 lavages": { local: 18, total: 4535 },
  "Lavage laveuses et séchoirs manuels": { local: 16, total: 329 },
  "Laveuse 25 kg n°3": { local: 60, total: 60 },
  "Laveuse 70 kg n°2 (droite)": { local: 55, total: 55 },
  "Laveuse 70kg n°1 (milieu)": { local: 58, total: 58 },
  "Séchoir electrolux T4900 n°1": { local: 66, total: 66 },
  "Séchoir electrolux T4900 n°2": { local: 28, total: 28 },
  "Séchoir electrolux T4900 n°3": { local: 46, total: 46 },
  "Table a détacher": { local: 0, total: 0 },
  "Lavage tunnel": { local: 28, total: 2699 },
  "1 tapis lavage industriel": { local: 24, total: 352 },
  "T1 (sortie presse vers navette)": { local: 6, total: 6 },
  "T10.1 (tapis reception séchoir)": { local: 10, total: 10 },
  "T10.2 (tapis reception séchoir)": { local: 8, total: 8 },
  "T10.3 (tapis reception séchoir)": { local: 14, total: 14 },
  "T11 (tapis de by pass)": { local: 4, total: 4 },
  "T12 (tapis icliné sortie en chariot)": { local: 3, total: 3 },
  "T13 (tapis sortie ampicker)": { local: 10, total: 10 },
  "T14 (tapis sortie ampicker)": { local: 17, total: 17 },
  "T17 (distribution postes alimentation GP)": { local: 6, total: 6 },
  "T23 (tapis VT sortie navette en dessous tapis séchoir 1)": { local: 3, total: 3 },
  "T3 (sortie presse vers ampicker)": { local: 6, total: 6 },
  "T4.1 (tapis de by pass VT)": { local: 2, total: 2 },
  "T4.2 (tapis de by pass VT)": { local: 0, total: 0 },
  "T4.3 (tapis de by pass VT)": { local: 2, total: 2 },
  "T5 (tapis chargement séchoir 1)": { local: 1, total: 1 },
  "T5.1 (tapis incliné VT)": { local: 2, total: 2 },
  "T5.10 (tapis alimentation poste 5 couvertures)": { local: 2, total: 2 },
  "T5.11 (tapis alimentation poste 2 VT)": { local: 47, total: 47 },
  "T5.12 (tapis engagement VT)": { local: 7, total: 7 },
  "T5.13 (tapis engagement VT)": { local: 3, total: 3 },
  "T5.2 (élévateur sortie séchoir)": { local: 50, total: 50 },
  "T5.4 (tapis sortie élévateur)": { local: 65, total: 65 },
  "T5.5 (tapis alimentation poste PP)": { local: 3, total: 3 },
  "T5.6 (tapis alimentation secteur résident)": { local: 6, total: 6 },
  "T5.7 (tapis alimentation poste 3 mixtes)": { local: 9, total: 9 },
  "T5.8 (tapis alimentation poste 4 éponges)": { local: 26, total: 26 },
  "T5.9A (tapis vers poste 3)": { local: 11, total: 11 },
  "T5.9B (tapis vers poste 5)": { local: 1, total: 1 },
  "T6 (tapis chargement séchoir 2)": { local: 1, total: 1 },
  "T7 (tapis chargement séchoir 3)": { local: 1, total: 1 },
  "T8 (tapis chargement séchoir 4)": { local: 1, total: 1 },
  "T9 (tapis chargement séchoir 5)": { local: 1, total: 1 },
  "2 tapis lavage résident": { local: 15, total: 40 },
  "T18 (tapis sortie essoreuse kannegiesser)": { local: 4, total: 4 },
  "T23 (tapis de by pass)": { local: 0, total: 0 },
  "T24.1 (tapis sortie séchoir)": { local: 7, total: 7 },
  "T24.2 (tapis sortie séchoir)": { local: 10, total: 10 },
  "T24.3 (tapis sortie séchoir)": { local: 3, total: 3 },
  "TS1 (tapis stockage avant séchoir)": { local: 0, total: 0 },
  "TS2 (tapis stockage avant séchoir)": { local: 0, total: 0 },
  "TS3 (tapis stockage avant séchoir)": { local: 0, total: 0 },
  "TS4 (tapis stockage avant séchoir)": { local: 0, total: 0 },
  "TS5 (tapis stockage avant séchoir)": { local: 1, total: 1 },
  "Ampicker": { local: 114, total: 114 },
  "Élévateur sortie presse lavatec": { local: 16, total: 16 },
  "Essoreuse kannegiesser": { local: 302, total: 302 },
  "Navette industriel (avant séchoir)": { local: 155, total: 155 },
  "Navette kannegiesser (avant séchoir)": { local: 392, total: 392 },
  "Presse jensen": { local: 206, total: 206 },
  "Presse lavatec tunnel 12": { local: 217, total: 217 },
  "Tunnel 10x35": { local: 317, total: 317 },
  "Tunnel LAVATEC": { local: 9, total: 560 },
  "Tunnel 10x50": { local: 273, total: 273 },
  "Tunnel 12x50": { local: 278, total: 278 },
  "Séchage": { local: 4, total: 1489 },
  "Séchoirs industriels": { local: 35, total: 1174 },
  "Aspiration peluche lavatec": { local: 2, total: 2 },
  "Séchoir industriel n°1": { local: 332, total: 332 },
  "Séchoir industriel n°2": { local: 219, total: 219 },
  "Séchoir industriel n°3": { local: 216, total: 216 },
  "Séchoir industriel n°4": { local: 200, total: 200 },
  "Séchoir industriel n°5": { local: 170, total: 170 },
  "Séchoirs résidents": { local: 36, total: 311 },
  "Armoire de gestion séchoir KÄNNEGIESSER": { local: 6, total: 6 },
  "Aspiration peluche kannegiesser": { local: 1, total: 1 },
  "Séchoir kannegiesser n°1": { local: 69, total: 69 },
  "Séchoir kannegiesser n°2": { local: 38, total: 38 },
  "Séchoir kannegiesser n°3": { local: 30, total: 30 },
  "Séchoir kannegiesser n°4": { local: 46, total: 46 },
  "Séchoir kannegiesser n°5": { local: 85, total: 85 },
  "Sodilec": { local: 60, total: 106 },
  "PC CE1": { local: 8, total: 8 },
  "PC CE2": { local: 9, total: 9 },
  "PC LN": { local: 4, total: 4 },
  "PC LR": { local: 5, total: 5 },
  "PC NT1": { local: 6, total: 6 },
  "PC NT2": { local: 1, total: 1 },
  "PC TD": { local: 2, total: 2 },
  "PC ZP1": { local: 10, total: 10 },
  "PC ZP2": { local: 1, total: 1 },
  "2 Finition": { local: 2, total: 15353 },
  "Ligne grand plat": { local: 171, total: 2314 },
  "Cercleuse automatique GP": { local: 253, total: 253 },
  "Convoyeur à rouleaux sortie cercleuse GP": { local: 2, total: 2 },
  "Empileur max twin stacker": { local: 274, total: 274 },
  "Engageuse GP": { local: 725, total: 725 },
  "Plieuse classic GP": { local: 583, total: 583 },
  "Sécheuse repasseuse GP": { local: 243, total: 243 },
  "Tapis sortie cercleuse GP": { local: 17, total: 17 },
  "Tapis sortie GP (amovible/translateur)": { local: 9, total: 9 },
  "Tapis sortie GP (après empileur alèzes)": { local: 1, total: 1 },
  "Tapis sortie GP (après empileur drap)": { local: 31, total: 31 },
  "Tapis sortie GP (avant cercleuse)": { local: 5, total: 5 },
  "Ligne petit plat": { local: 159, total: 1542 },
  "Cercleuse PP": { local: 346, total: 346 },
  "Empileur bottom-up folder": { local: 30, total: 30 },
  "Engageuse PP": { local: 73, total: 73 },
  "Plieuse classic PP": { local: 204, total: 204 },
  "Plieuse napkin PP": { local: 531, total: 531 },
  "Sécheuse repasseuse PP": { local: 199, total: 199 },
  "Ligne VT et non pucé": { local: 25, total: 11495 },
  "Convoyeurs et tapis": { local: 13, total: 556 },
  "A - A1 convoyeur sortie maximat 1 après roll off": { local: 3, total: 3 },
  "AA - A11 roll off (convoyeur téléscopique sortie maximat 1)": { local: 35, total: 35 },
  "AAA - A12 convoyeur sortie maximat 1 ": { local: 7, total: 7 },
  "B - B12 convoyeur sortie maximat 2 ": { local: 10, total: 10 },
  "BB - B11 roll off (convoyeur téléscopique sortie maximat 2)": { local: 112, total: 112 },
  "C - B1 convoyeur sortie maximat 2 après roll off": { local: 30, total: 30 },
  "D - Tapis sortie maximat et PP": { local: 4, total: 4 },
  "E - Tapis sortie maximat et PP": { local: 0, total: 0 },
  "F - Tapis sortie maximat et PP": { local: 7, total: 7 },
  "G - Convoyeur à rouleau d\'angle avant centreur": { local: 3, total: 3 },
  "H - D1 Centreur et convoyeur": { local: 66, total: 66 },
  "I - S1 convoyeur a rouleaux après centreur": { local: 27, total: 27 },
  "J - Tapis avant filmeuse PP VT (tapis bleu)": { local: 5, total: 5 },
  "K - Tapis avant filmeuse PP VT (tapis vert)": { local: 17, total: 17 },
  "L - Convoyeur a rouleaux d\'angle avant filmeuse PP": { local: 7, total: 7 },
  "M - Tapis entre filmeuse et tunnel de lecture": { local: 3, total: 3 },
  "N - Convoyeur à bandes tunnel de lectures": { local: 29, total: 29 },
  "O - Transfert 90° sous étiqueteuse": { local: 152, total: 152 },
  "P - Tapis reception vt (après étiqueteuse)": { local: 13, total: 13 },
  "Q - Convoyeur à rouleaux d\'angle sortie étiqueteuse non pucé": { local: 9, total: 9 },
  "QQ - Tapis sortie étiqueteuse non pucé": { local: 4, total: 4 },
  "Étiqueteuse VT": { local: 1137, total: 1137 },
  "Filmeuse PP VT": { local: 2617, total: 2617 },
  "Ligne de tri système Métricon": { local: 162, total: 3995 },
  "1 convoyeur à chaine Métricon": { local: 259, total: 3311 },
  "M1(reception sortie poste 1 et 2)": { local: 6, total: 6 },
  "M10 (avant entrée dans tri A)": { local: 57, total: 57 },
  "M11 (distribution tri A)": { local: 35, total: 35 },
  "M12.1 (barre de stockage tri A)": { local: 1, total: 1 },
  "M12.10 (barre de stockage tri A)": { local: 0, total: 0 },
  "M12.11 (barre de stockage tri A)": { local: 3, total: 3 },
  "M12.2 (barre de stockage tri A)": { local: 4, total: 4 },
  "M12.3 (barre de stockage tri A)": { local: 3, total: 3 },
  "M12.4 (barre de stockage tri A)": { local: 25, total: 25 },
  "M12.5 (barre de stockage tri A)": { local: 12, total: 12 },
  "M12.6 (barre de stockage tri A)": { local: 11, total: 11 },
  "M12.7 (barre de stockage tri A)": { local: 10, total: 10 },
  "M12.8 (barre de stockage tri A)": { local: 2, total: 2 },
  "M12.9 (barre de stockage tri A)": { local: 5, total: 5 },
  "M13 (sortie barre de stockage tri A)": { local: 31, total: 31 },
  "M14 (buffer entre tri A et tri B)": { local: 235, total: 235 },
  "M15 (retour VT vers tri A)": { local: 13, total: 13 },
  "M16 (distribution tri B)": { local: 88, total: 88 },
  "M17.1 (barre de stockage tri B)": { local: 7, total: 7 },
  "M17.2 (barre de stockage tri B)": { local: 6, total: 6 },
  "M17.3 (barre de stockage tri B)": { local: 7, total: 7 },
  "M17.4 (barre de stockage tri B)": { local: 5, total: 5 },
  "M17.5 (barre de stockage tri B)": { local: 1, total: 1 },
  "M17.6 (barre de stockage tri B)": { local: 4, total: 4 },
  "M17.7 (barre de stockage tri B)": { local: 6, total: 6 },
  "M17.8 (barre de stockage tri B)": { local: 11, total: 11 },
  "M18 (sortie tri B)": { local: 413, total: 413 },
  "M19 (recyclage phase de tri entrée sortie tri B)": { local: 238, total: 238 },
  "M2 (transport entre sortie 1/2 et 3/4)": { local: 3, total: 3 },
  "M20 (descente VT trié)": { local: 46, total: 46 },
  "M21 (distribution VT vers maximats)": { local: 47, total: 47 },
  "M22 (stockage devant maximat 1)": { local: 10, total: 10 },
  "M23 (stockage devant maximat 2)": { local: 57, total: 57 },
  "M24.1 (sortie cintre vide maximat 1)": { local: 62, total: 62 },
  "M24.2 (sortie cintre vide maximat 2)": { local: 50, total: 50 },
  "M25 (remonté cintre vide pour stockage)": { local: 204, total: 204 },
  "M26 (distribution cintre pour stockage)": { local: 60, total: 60 },
  "M27.1 (stockage cintres vide)": { local: 34, total: 34 },
  "M27.2 (stockage cintres vide)": { local: 25, total: 25 },
  "M27.3 (stockage cintres vide)": { local: 34, total: 34 },
  "M27.4 (stockage cintres vide)": { local: 20, total: 20 },
  "M28 (sortie stockage cintres vide)": { local: 63, total: 63 },
  "M29 (alimentation cintre au dessus PP)": { local: 165, total: 165 },
  "M3 (récupération engagement 3/4 et M2)": { local: 16, total: 16 },
  "M30 (alimentation cintre au dessus tapi VT)": { local: 123, total: 123 },
  "M31 (distribution cintre vide sur poste d\'engagement)": { local: 141, total: 141 },
  "M4 (arrivée vers entrée tunnel de finition)": { local: 10, total: 10 },
  "M5 (sortie tunnel)": { local: 29, total: 29 },
  "M6 (montée vers étage)": { local: 365, total: 365 },
  "M7 (sortie M6 jusqu\'a scanner L21)": { local: 153, total: 153 },
  "M8 (passage devant sortie GTI)": { local: 24, total: 24 },
  "M9 (sortie engagement poste GTI)": { local: 3, total: 3 },
  "MF1:1 (poste engagement 1)": { local: 2, total: 2 },
  "MF1:2 (poste engagement 2)": { local: 7, total: 7 },
  "MF1:3 (poste engagement 3)": { local: 19, total: 19 },
  "MF1:4 (poste engagement 4)": { local: 13, total: 13 },
  "MF2:1 (sortie poste engagement 1)": { local: 0, total: 0 },
  "MF2:2 (sortie poste engagement 2)": { local: 4, total: 4 },
  "MF2:3 (sortie poste engagement 3)": { local: 11, total: 11 },
  "MF2:4 (sortie poste engagement 4)": { local: 13, total: 13 },
  "2 Mise sur cintre et système informatique": { local: 24, total: 522 },
  "Armoire électrique métric": { local: 8, total: 8 },
  "Cintres": { local: 91, total: 91 },
  "MCPC": { local: 14, total: 14 },
  "MFS (serveur)": { local: 8, total: 8 },
  "Poste d\'engagement magasin": { local: 16, total: 16 },
  "Poste d\'engagement VT n°1 (metrifeed)": { local: 101, total: 101 },
  "Poste d\'engagement VT n°2 (metrifeed)": { local: 60, total: 60 },
  "Poste d\'engagement VT n°3 (metrifeed)": { local: 82, total: 82 },
  "Poste d\'engagement VT n°4 (metrifeed)": { local: 109, total: 109 },
  "Poste informatique metricon (baie a côté du bureau)": { local: 5, total: 5 },
  "Poste informatique metricon (petite armoire en dessous bureau)": { local: 1, total: 1 },
  "Poste lecture VT (vers centreur)": { local: 3, total: 3 },
  "Plieuses": { local: 37, total: 2765 },
  "Plieuse VT 1": { local: 1349, total: 1349 },
  "Plieuse VT 2": { local: 1379, total: 1379 },
  "Tunnel de finition": { local: 343, total: 343 },
  "Tunnel de lecture ": { local: 57, total: 57 },
  "3 Linge séché": { local: 17, total: 2813 },
  "Cercleuse indépendante": { local: 1, total: 411 },
  "Cercleuse couverture": { local: 136, total: 136 },
  "Cercleuse Lapauw": { local: 274, total: 274 },
  "Ligne couverture": { local: 22, total: 291 },
  "Empileur couverture": { local: 48, total: 48 },
  "Plieuse couverture": { local: 221, total: 221 },
  "Ligne plieuses eponges": { local: 108, total: 1237 },
  "Cercleuse automatique éponges": { local: 580, total: 580 },
  "Plieuse éponge (esclave)": { local: 252, total: 252 },
  "Plieuse éponge (maitre)": { local: 297, total: 297 },
  "Petit plat résident": { local: 82, total: 486 },
  "Empileur classic résident ": { local: 13, total: 13 },
  "Plieuse classic résident": { local: 90, total: 90 },
  "Plieuse napkin résident": { local: 134, total: 134 },
  "Sécheuse repasseuse résident": { local: 167, total: 167 },
  "Poste bipage 1": { local: 17, total: 122 },
  "Poste 1 bipage ": { local: 105, total: 105 },
  "Poste bipage 2": { local: 10, total: 64 },
  "Poste 2 bipage ": { local: 54, total: 54 },
  "Poste marquage": { local: 31, total: 31 },
  "Table à repasser N°1": { local: 14, total: 14 },
  "Table à repasser N°2": { local: 7, total: 7 },
  "Tapis": { local: 128, total: 133 },
  "Roll off sortie éponges (convoyeur téléscopique)": { local: 1, total: 1 },
  "Tapis avant cercleuse couverture manuelle": { local: 0, total: 0 },
  "Tapis N°2 récolte plieuse éponges": { local: 2, total: 2 },
  "Tapis N°3 recolte plieuse éponges": { local: 0, total: 0 },
  "Tapis N°4 recolte plieuse éponges": { local: 2, total: 2 },
  "4 Expedition": { local: 180, total: 307 },
  "Étiqueteuse navette": { local: 104, total: 104 },
  "Étiqueteuse QR code navette": { local: 14, total: 14 },
  "Poste de lecture (RAMSES)": { local: 9, total: 9 },
  "Autres": { local: 507, total: 538 },
  "Autre": { local: 31, total: 31 },
  "Batiment": { local: 265, total: 301 },
  "Sanitaires": { local: 26, total: 26 },
  "Self": { local: 5, total: 7 },
  "PC commande repas": { local: 2, total: 2 },
  "Système d\'alarme incendie": { local: 3, total: 3 },
  "Formation": { local: 3, total: 3 },
  "Magasin": { local: 121, total: 187 },
  ".Poste marquage 5 (vers caillebotis)": { local: 11, total: 18 },
  "Imprimante étiquette CAB 1 (gauche)": { local: 1, total: 1 },
  "Imprimante étiquette CAB 2 (droite)": { local: 3, total: 3 },
  "Thermocolleuse double": { local: 1, total: 1 },
  "Thermocolleuse Thermopatch 1 (gauche)": { local: 0, total: 0 },
  "Thermocolleuse Thermopatch 2 (droite)": { local: 2, total: 2 },
  "Imprimante étiquette VT SQUIX": { local: 13, total: 13 },
  "Imprimante KONICA MINOLTA BUSIN": { local: 8, total: 8 },
  "Machine a coudre 1": { local: 1, total: 1 },
  "Machine a coudre 2": { local: 0, total: 0 },
  "Thermocolleuse Thermopatch NL-15-SQR poste 1(gauche)": { local: 8, total: 8 },
  "Thermocolleuse Thermopatch NL-15-SQR poste 2(droite)": { local: 18, total: 18 },
  "Technique": { local: 21, total: 805 },
  "Cuve à sel": { local: 13, total: 13 },
  "local chaufferie": { local: 29, total: 268 },
  "Accélérateur 1": { local: 0, total: 0 },
  "Accélérateur 2": { local: 0, total: 0 },
  "Bâche alimentaire chaudière": { local: 147, total: 147 },
  "Chaudière chauffage": { local: 16, total: 16 },
  "Chaudière vapeur": { local: 75, total: 75 },
  "Vase d\'expansion 1 (côté mur)": { local: 1, total: 1 },
  "Vase d\'expansion 2 ": { local: 0, total: 0 },
  "local eau": { local: 53, total: 116 },
  "Adoucisseur N°1 (bleu gauche)": { local: 0, total: 0 },
  "Adoucisseur N°2 (bleu droite)": { local: 1, total: 1 },
  "Adoucisseur N°3 (chrome gauche)": { local: 0, total: 0 },
  "Adoucisseur N°4 (chrome droite)": { local: 2, total: 2 },
  "Ballon d\'expantion eau forage filtée (gris)": { local: 3, total: 3 },
  "Ballon d\'expantion eau process réchauffée (blanc)": { local: 1, total: 1 },
  "Cuve eau forage (orange droite)": { local: 1, total: 1 },
  "Cuve eau rechaufée (orange gauche)": { local: 5, total: 5 },
  "Dégrilleur": { local: 6, total: 6 },
  "Échangeur BAMO": { local: 18, total: 18 },
  "Pompe acide sulfurique": { local: 15, total: 15 },
  "Surpresseur N°1 eau de forage filtrée": { local: 2, total: 2 },
  "Surpresseur N°1 eau de process réchauffée": { local: 2, total: 2 },
  "Surpresseur N°2 eau de forage filtrée": { local: 3, total: 3 },
  "Surpresseur N°2 eau de process réchauffée": { local: 1, total: 1 },
  "Surpresseur N°3 eau de forage filtrée": { local: 2, total: 2 },
  "Surpresseur N°3 eau de process réchauffée": { local: 1, total: 1 },
  "local lessiviel": { local: 106, total: 270 },
  "Armoire électrique Laundry X-Pert": { local: 3, total: 3 },
  "Armoire Flux-Multi (pompe laveuses)": { local: 2, total: 2 },
  "Armoire Flux-Star (T3)": { local: 1, total: 41 },
  "Pompe pos1 - T3 - Lunosept concentrate": { local: 1, total: 1 },
  "Pompe pos10 - T3 - Ultimate forte": { local: 8, total: 8 },
  "Pompe pos11 - T3 - Ultimate neutra": { local: 0, total: 0 },
  "Pompe pos12 - T3 - Aquadiv": { local: 0, total: 0 },
  "Pompe pos3 - T3 - Osmaflux ideal": { local: 5, total: 5 },
  "Pompe pos4 - T3 - Smart Alkaline": { local: 0, total: 0 },
  "Pompe pos5 - T3 - Non utilisée": { local: 5, total: 5 },
  "Pompe pos6 - T3 - Osmaflux ideal": { local: 6, total: 6 },
  "Pompe pos7 - T3 - Bisoft Duo": { local: 3, total: 3 },
  "Pompe pos9 - T3 - Ultimate forte": { local: 12, total: 12 },
  "Douche de sécurité": { local: 3, total: 3 },
  "Pompe P1 Tunnel 1 Osmaflux ideal": { local: 22, total: 22 },
  "Pompe P1 Tunnel 2 Osmaflux ideal": { local: 24, total: 24 },
  "Pompe P2 Tunnel 1 ULTIMATE FORTE": { local: 17, total: 17 },
  "Pompe P2 Tunnel 2 ULTIMATE FORTE": { local: 24, total: 24 },
  "Pompe P3 Tunnel 1 Smart Alkaline": { local: 3, total: 3 },
  "Pompe P3 Tunnel 2 Smart Alkaline": { local: 1, total: 1 },
  "Pompe P4 Tunnel 1 ULTIMATE NEUTRA": { local: 6, total: 6 },
  "Pompe P4 Tunnel 2 ULTIMATE NEUTRA": { local: 3, total: 3 },
  "Pompe P5 Tunnel 1 AQUADIV (anciennement bisoft duo)": { local: 2, total: 2 },
  "Pompe P5 Tunnel 2 AQUADIV(anciennement bisoft duo)": { local: 2, total: 2 },
  "Pompe P6 Tunnel 1 ULTIMATE FORTE": { local: 11, total: 11 },
  "local Pneumatique": { local: 10, total: 42 },
  "Compresseur 2018 L45RS (droite côté CTA)": { local: 11, total: 11 },
  "Compresseur 2020 L45RS (gauche côté nappe résident)": { local: 7, total: 7 },
  "Deshuileur": { local: 2, total: 2 },
  "Reservoir 1000 litres": { local: 0, total: 0 },
  "Reservoir 1500 litres": { local: 0, total: 0 },
  "Sécheur d\'air": { local: 12, total: 12 },
  "local ventilation": { local: 3, total: 75 },
  "Centrale de traitement d\'air finition artisanal (neuve)": { local: 29, total: 29 },
  "Centrale de traitement d\'air finition industrielle (existante)": { local: 7, total: 7 },
  "Centrale de traitement d\'air linge sale aspiration": { local: 25, total: 25 },
  "Groupe froid (vers TGBT)": { local: 0, total: 0 },
  "Groupe froid extérieur GTI": { local: 11, total: 11 },
};
