const lieuData = {
  "types": [
    "Aiguillage",
    "Alarme",
    "Alvéole bloqué en descente",
    "Alvéole bloquée",
    "Arbre HS",
    "Arrêt d'urgence",
    "Automatisme",
    "Autres",
    "Bande",
    "Bobine emmêlée/coincée",
    "Bourrage",
    "Bourrage avant TC",
    "Bourrage de linge",
    "Bourrage TC",
    "Bruit",
    "Bruit anormal",
    "Bruleur",
    "Capteur",
    "Changement rouleau d'encre",
    "Changement rouleau d'étiquette",
    "Changement rouleau film Bas",
    "Changement rouleau film Haut",
    "Cintre cassé",
    "Cintre chute",
    "Cintre croisé",
    "Cintres coincés",
    "Crochet cassé",
    "Décalage",
    "Decolleur",
    "Doigt / taquet cassé",
    "Double passe",
    "Electrique",
    "Empilage",
    "F01",
    "Film déchiré ou cassé",
    "Fuite air",
    "Fuite eau",
    "Fuite huile",
    "Galet tunnel HS",
    "Gaz",
    "Humaine",
    "Hydraulique",
    "Informatique",
    "Manque d'eau",
    "Mauvais pliage / Pas de pliage",
    "Mauvais réglage",
    "Mauvaise soudure",
    "Mécanique ",
    "Membrane percée",
    "Moteur HS",
    "Moumoute capteur",
    "Navette cassée",
    "Pas de démarrage",
    "Pile",
    "Plomberie",
    "Plus de consommable",
    "Pneu déjanté",
    "Pneumatique",
    "Pompe désamorcée",
    "Préventif",
    "Qualité",
    "Raccord/Tuyau cassé",
    "Rebut(s)",
    "Réglage",
    "Ressort cassé",
    "Roulement HS",
    "Sacs",
    "Sécurité",
    "Sling bloqué",
    "Sling mal ouvert/fermé",
    "Sonde",
    "Tambour rotation",
    "Tapis",
    "Téléphonie",
    "Trolley bloqué",
    "Vapeur",
    "Z.Plus d'encre(Osbelete)",
    "Z.Plus d'étiquette(Osbelete)"
  ],
  "causes": [
    "Aiguillage",
    "Arrêt d'urgence",
    "Automatisme",
    "Autre",
    "Bande cassée",
    "Bande(s) decalé(s)",
    "Bandes",
    "Bobine emmêlée/coincée",
    "Bourrage linge",
    "Capteur",
    "Capteur déréglé",
    "Chaine bloquée / cassée / détendue",
    "Cintre puce HS",
    "Cintres croisés",
    "Courbe métric usée",
    "Courroie usée / détendue",
    "Décalage",
    "Electrique",
    "Erreur de programmation",
    "Erreur humaine",
    "Fil coupé",
    "Frein déréglé ou cassé",
    "Fuite",
    "Linge devant cellule",
    "Manque de formation du personnel",
    "Mécanique",
    "Multiples",
    "Niveau",
    "Pièce tordu",
    "Plus d'encre",
    "Plus d'étiquette",
    "Plus de bobine",
    "Plus de film",
    "Plus de produit",
    "Poussière / Salissure",
    "Pressostat bouché",
    "Rail usé",
    "Réglage",
    "Relais thermique",
    "Sacs",
    "Sécurité",
    "Sling en travers",
    "Sling mal ouvert/fermé",
    "Surchauffe",
    "Taquet cassé",
    "Téflon usé",
    "Tuyau bouché",
    "Usures matériels",
    "Vis déssérée ou cassée",
    "Volume de linge trop important",
    "Z.Chaine cassée(Obselete)",
    "Z.Chaine(Obselete)",
    "Z.Cintre(Obselete)",
    "Z.Crochet cassé(Obselete)",
    "Z.Erreur de programmation(Obselete)",
    "Z.Sécurité(Obselete)",
    "Z.Verin pneumatique(Osbelete)"
  ]
};