const Regroups = {
    "Test": {
        "Autres": [],
        "Autre": []
    },
    "Séchoirs kannegiesser": {
        "Armoire de gestion séchoir KÄNNEGIESSER": [],
        "Aspiration peluche kannegiesser": [],
        "Séchoir kannegiesser n°1": [],
        "Séchoir kannegiesser n°2": [],
        "Séchoir kannegiesser n°3": [],
        "Séchoir kannegiesser n°4": [],
        "Séchoir kannegiesser n°5": []
    },
    "Séchoirs industriels": {
        "Séchoir industriel n°1": [],
        "Séchoir industriel n°2": [],
        "Séchoir industriel n°3": [],
        "Séchoir industriel n°4": [],
        "Séchoir industriel n°5": []
    },
    "Tri industriel": {
        "futurail": [],
        "Aiguillage 3 voies sortie nappe": [],
        "Aiguillage entrée voie 1": [],
        "Aiguillage entrée voie 2": [],
        "Aiguillage entrée voie 3": [],
        "Aiguillage entrée voie 4": [],
        "Aiguillage sortie voie 1": [],
        "Aiguillage sortie voie 2": [],
        "Aiguillage sortie voie 3": [],
        "Aiguillage sortie voie 4": [],
        "Chargeur de sac (sling)": [],
        "Basculeur sling vide": [],
        "D2 dechargeur tunnel 12": [],
        "D1 dechargeur tunnel 10": [],
        "Décroche sacs": [],
        "Redresseur sling vide": [],
        "Alvéole 01": [],
        "Alvéole 02": [],
        "Alvéole 03": [],
        "Alvéole 04": [],
        "Alvéole 05": [],
        "Alvéole 06": [],
        "Alvéole 07": [],
        "Alvéole 08": [],
        "Alvéole 09": [],
        "Alvéole 10": [],
        "Alvéole 11": [],
        "Alvéole 12": []
    },
    "Tri résident": {
        "Basculeur sling vide": [],
        "D3 dechargeur tunnel 3": [],
        "D4 dechargeur laveuses": [],
        "Redresseur sling vide": [],
        "Alvéole 1": [],
        "Alvéole 2": [],
        "Alvéole 3": [],
        "Alvéole 4": [],
        "Alvéole 5": [],
        "Alvéole 6": [],
        "Alvéole 7": [],
        "Alvéole 8": []
    },
    "Tapis lavage industriel": {
        "T1 (sortie presse vers navette)": [],
        "T10.1 (tapis reception séchoir)": [],
        "T10.2 (tapis reception séchoir)": [],
        "T10.3 (tapis reception séchoir)": [],
        "T11 (tapis de by pass)": [],
        "T12 (tapis icliné sortie en chariot)": [],
        "T13 (tapis sortie ampicker)": [],
        "T14 (tapis sortie ampicker)": [],
        "T17 (distribution postes alimentation GP)": [],
        "T23 (tapis VT sortie navette en dessous tapis séchoir 1)": [],
        "T3 (sortie presse vers ampicker)": [],
        "T4.1 (tapis de by pass VT)": [],
        "T4.2 (tapis de by pass VT)": [],
        "T4.3 (tapis de by pass VT)": [],
        "T5 (tapis chargement séchoir 1)": [],
        "T5.1 (tapis incliné VT)": [],
        "T5.10 (tapis alimentation poste 5 couvertures)": [],
        "T5.11 (tapis alimentation poste 2 VT)": [],
        "T5.12 (tapis engagement VT)": [],
        "T5.13 (tapis engagement VT)": [],
        "T5.2 (élévateur sortie séchoir)": [],
        "T5.4 (tapis sortie élévateur)": [],
        "T5.5 (tapis alimentation poste PP)": [],
        "T5.6 (tapis alimentation secteur résident)": [],
        "T5.7 (tapis alimentation poste 3 mixtes)": [],
        "T5.8 (tapis alimentation poste 4 éponges)": [],
        "T5.9A (tapis vers poste 3)": [],
        "T5.9B (tapis vers poste 5)": [],
        "T6 (tapis chargement séchoir 2)": [],
        "T7 (tapis chargement séchoir 3)": [],
        "T8 (tapis chargement séchoir 4)": [],
        "T9 (tapis chargement séchoir 5)": []
    },
    "test": {
        "1 Controle entré": []
    },
    "Alvéoles Industriel": {
        "Alvéole 01": [],
        "Alvéole 02": [],
        "Alvéole 03": [],
        "Alvéole 04": [],
        "Alvéole 05": [],
        "Alvéole 06": [],
        "Alvéole 07": [],
        "Alvéole 08": [],
        "Alvéole 09": [],
        "Alvéole 10": [],
        "Alvéole 11": [],
        "Alvéole 12": []
    },
    "Nappe Industriel": {
        "Basculeur sling vide": [],
        "Chargeur de sac (sling)": [],
        "D1 dechargeur tunnel 10 ": [],
        "D2 dechargeur tunnel 12": [],
        "Décroche sacs": [],
        "LA1 (ascenceur avant voie de recyclage)": [],
        "Redresseur sling vide": [],
        "Tampon avant tunnel 10 (D1)": [],
        "Tampon avant tunnel 12 (D2)": [],
        "Tampon recyclage": [],
        "Tampon sling vide avant chargeur": [],
        "Tampon sling vide basculé": [],
        "Tampon sling vide sortie redresseur": [],
        "VC2 (descenceur avant tunnels)": [],
        "Voie 1": [],
        "Voie 2": [],
        "Voie 3": [],
        "Voie 4": [],
        "Voie 5": [],
        "Tapis avant tapis incliné chargeur": [],
        "Tapis derrière alvéoles 1 a 5": [],
        "Tapis derrière alvéoles 11": [],
        "Tapis derrière alvéoles 12 ": [],
        "Tapis derrière alvéoles 6 a 10": [],
        "Tapis devant alvéoles": [],
        "Tapis incliné avant chargeur": [],
        "Tapis tri devant alvéoles entre industriel et résindent": [],
        "Tapis tri devant alvéoles résident": []
    },
    "Metric": {
        "Armoire électrique métric": [],
        "Cintres": [],
        "MCPC": [],
        "MFS (serveur)": [],
        "Poste informatique metricon (baie a côté du bureau)": [],
        "Poste informatique metricon (petite armoire en dessous bureau)": [],
        "Poste lecture VT (vers centreur)": []
    }
};